### ISSUE TITLE
Undefined names: pd, sns, active_imports in demo.py

### ISSUE THREAD

**Issue by cclauss** [8080labs/pyforest#10]
[flake8](http://flake8.pycqa.org) testing of https://github.com/8080labs/pyforest on Python 3.7.1

$ __flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics__
```
./examples/demo.py:5:6: F821 undefined name 'pd'
df = pd.read_csv("titanic.csv")
     ^
./examples/demo.py:8:1: F821 undefined name 'sns'
sns.distplot(df.Age)
^
./examples/demo.py:11:1: F821 undefined name 'active_imports'
active_imports()
^
3     F821 undefined name 'pd'
3
```

**Comment by tkrabel** [comment]
`demo.py` is supposed to be shown in a jupyter notebook, where you don't need to import pyforest because of the auto-import.
Now, the reason why `demo.py` is not an `.ipynb` is that we use jupytext in order to sync ipynb files with py files and only check in the py files
