### ISSUE TITLE
Add TextBlob to NLP

### ISSUE THREAD

**Issue by rohanmohapatra** [8080labs/pyforest#17]
---
name: ✨ Feature Request
about: Add TextBlob to NLP Imports
---

# What feature should be added?
Text Blob is a simple text processing library that helps in NLP tasks such as part-of-speech tagging, noun phrase extraction, sentiment analysis, classification, translation, and more.
# Why should this feature be added?

Features
- Noun phrase extraction
- Part-of-speech tagging
- Sentiment analysis
- Classification (Naive Bayes, Decision Tree)
- Language translation and detection powered by Google Translate
- Tokenization (splitting text into words and sentences)
- Word and phrase frequencies
- Parsing
- n-grams
- Word inflection (pluralization and singularization) and lemmatization
- Spelling correction
- Add new models or languages through extensions
- WordNet integration

Source : [TextBlob](https://textblob.readthedocs.io/en/dev/)

**Comment by RafeyIqbalRahman** [comment]
@FlorianWetschoreck TextBlob has been added. You may close this issue now. :)

**Comment by FlorianWetschoreck** [comment]
@RafeyIqbalRahman great, thank you :)

**Comment by RafeyIqbalRahman** [comment]
You're welcome. :)
