### ISSUE TITLE
trai_test_split import deprecated

### ISSUE THREAD

**Issue by solalatus** [8080labs/pyforest#18]
In 
https://github.com/8080labs/pyforest/blob/66fbb355afb73c041692f9361970cc75bb8a265d/src/pyforest/_imports.py#L62
the import is deprecared, it runs into the following warning:

`DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)`

As per new Scikit structure, the new import is:
`from sklearn.model_selection import train_test_split`

It would be nice, if you could update it!

Many thanks!

**Comment by tkrabel** [comment]
Thanks for the comment! I added the new import to the package :)
