### ISSUE TITLE
Custom families / local files

### ISSUE THREAD

**Issue by henryiii** [8080labs/pyforest#19]
It would be nice to have a way to list files in a user's home directory, say in `~/.config/pyforest/`, as well add domain specific modules that could be loaded. I'm interested in setting up the HEP (high energy physics) imports, but some of them are not of general interest.

**Comment by tkrabel** [comment]
Hi @henryiii 
thanks for your input. I like the idea and developed a first version. It's currently on the `user_specific_imports` branch, where you can already check it out if you want (#20). 

After the next launch of pyforest, it will create `~/.pyforest/user_imports.py`, where you can add as many imports as you want. Please note: the imports in `~/.pyforest/user_imports.py` overwrite the ones in `pyforest._imports.py` in case of name conflicts.

So, for example, if you save `import cryptography as pd` in the py file, it will overwrite the `import pandas as pd` import from `pyforest._imports.py`

Let me know what you think of the feature.

**Comment by tkrabel** [comment]
It's merged into master now
