### ISSUE TITLE
Custom families

### ISSUE THREAD

**Issue by henryiii** [8080labs/pyforest#21]
This is the other half of #19. It would be nice to be able to make custom families as part of pyforest. For example:

```
from pyforest import * # All general purpose libraries (as it is now)
from pyforest.hep import * # High Energy Physics specific libraries
from pyforest.ml import * # Machine learning specific libraries
from pyforest.bio import * # Biopython (etc)

# optional
from pyforest.all import * # Import all groups and general libraries too
```

If this is doable and a good idea, I can help contribute `hep`'s imports, maybe ml too. :)

**Comment by henryiii** [comment]
(This could also be approached from the other direction - `from pyforest import *` would import everything and then the smaller groups would be either mostly for organization or if a user wanted to be explicit with a smaller collection - maybe this would be more in line with pyforest's philosophy - I'm not sure how often name conflicts might arise as it grows).

**Comment by henryiii** [comment]
When building the list, it's not that awful, 10ish items or so currently. Should I just mark out a section HEP and submit a PR? Or are one of the two ideas above better?

**Comment by tkrabel** [comment]
Hey @henryiii ,

thanks for the PR and for your commitment, but I think the HEP imports are quite niche. :) 
Pls use the `~/.pyforest/user_imports.py` file for these imports. Or do you think they should be included in the package? If so, why?

Best

**Comment by henryiii** [comment]
That's the idea of custom families. There are a lot of users that would benefit from a shared list of common imports, but it would be a subset of users (since all PyForest users will not need to open a ROOT file, etc). So therefore `from pyforest.hep import *` could service this community (and I could see others, like the mentioned bio, along with astro and probably more).

What about a PyForest extension mechanism? So if you did pip install pyforest-hep, you would get more imports (similar to the way `pytest` works with `pytest-benchmarks`, etc.). Scikit-HEP could then maintain a `pyforest-hep` package. This might even be nicer, since it does not change what a user has to type (on of the points of PyForest), just what they have to require/install.

**Comment by 8080labs** [comment]
Hey @henryiii,
sorry for the late response. So I took a look at your suggestion again. Bundling topic related imports in one module seems to be a better way to go about the problem to make deviations form pyforest's basic imports more deliberate. 
Could you bundle the HEP libraries in a separate module `hep` and submit a PR? :)
Cheers and thanks for your patience!
Tobias

**Comment by henryiii** [comment]
It'll take a little time, we are building flow monitors for ventilators for the local hospital. When I do have time, is there an example of a separate module yet or would I be adding the first?

**Comment by tkrabel** [comment]
You'd be the pioneer in this regard.
