### ISSUE TITLE
Help messages

### ISSUE THREAD

**Issue by henryiii** [8080labs/pyforest#23]
I've noticed that the help messages are hidden for objects. Would it be possible, when loading an object, to copy the docstring in, as well? Since you are Python 3 only, you could even copy in the `__signature__`, I think.

```python
In [1]: UnitRegistry()
Out[1]: <pint.registry.UnitRegistry at 0x1068a6d50>

In [2]: UnitRegistry?
Signature:   UnitRegistry(*args, **kwargs)
Type:        LazyImport
String form: active pyforest.LazyImport of <class 'pint.registry.UnitRegistry'>
File:        /usr/local/lib/python3.7/site-packages/pyforest/_importable.py
Docstring:   <no docstring>
```

**Comment by tkrabel** [comment]
Great stuff!
I will have a look at your PR soon 👍
