### ISSUE TITLE
Add pyforest to first CODE cell and not markdown or other

### ISSUE THREAD

**Issue by 8080labs** [8080labs/pyforest#27]
Currently, pyforest will add the import_statements to the first Jupyter cell. pyforest assumes that this cell is a code cell. However, it will currently also add the code if the cell is not a code cell.

It would be better, if pyforest searches for the first CODE cell.

This enables a situation where the user also has Markdown cells in the Notebook and he wants the first cell to be a Markdown cell (or similar).

**Comment by tnwei** [comment]
Seconding this! I'm sure many of use have the first cell in markdown as the title block. Wondering what type of fix would be needed? Not familiar with JS, but I'm assuming this chunk in `src/pyforest/_importable.py ` is where it needs to go:
```
display(
        Javascript(
            """
        if (window._pyforest_update_imports_cell) {{ window._pyforest_update_imports_cell({!r}); }}
    """.format(
                "\n".join(statements)
            )
        )
    )
```

**Comment by 8080labs** [comment]
Happy to hear that you also thought about this :)


I am afraid, that the fix needs to be in JS and not in Python.
Most likely somewhere around here in `src/pyforest/static/utils.js`
```
	function setup_lab(notebookTracker) {
		window._pyforest_update_imports_cell = function (imports_string) {
			var cell = notebookTracker.currentWidget.model.cells.get(0).value;
			cell.text = get_new_cell_content(imports_string, cell.text);
		};
	}

	function setup_notebook(Jupyter) {
		window._pyforest_update_imports_cell = function (imports_string) {
			var cell_doc = Jupyter.notebook.get_cell(0).code_mirror.getDoc();
			cell_doc.setValue(get_new_cell_content(imports_string, cell_doc.getValue()));
		};
	}
```

Because this is the position where pyforest selects the cell to be updated. Currently, it is just the first cell.

**Comment by tnwei** [comment]
Mmmm. Adding this and using the return value should do it. https://gist.github.com/tnwei/6005afe55cb8898ba87daa36fce23392

**Comment by tnwei** [comment]
Submitted a pull request, feedback appreciated!

**Comment by tkrabel** [comment]
Just for the protocol: the last state of your PR #29 was that you need to find a way to make your PR work on JupyterLab. Any progress here? Can someone else help?

**Comment by tkrabel** [comment]
Never mind everyone, I added the feature myself with PR #46.
