### ISSUE TITLE
Does not install on Python 3.5

### ISSUE THREAD

**Issue by ecederstrand** [8080labs/pyforest#3]
### Environment

* Operating System:
* Python Version: `Python 3.5.5`
* How did you install pyforest: `pip install pyforest`
* Python packages: This is a clean env

### Description of Issue

`setup.cfg` just mentions Python as a requirement, but with no specific version requirements, so I (and pip) expected to be able to install it on any currently supported Python version. Python 3.5 is still actively supported.

This project contains f-strings which were introduced in Python 3.6, so I get this stack trace when I try to install:

```python
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-lxgsgu9_/pyforest/setup.py", line 10, in <module>
        from src.pyforest.auto_import import setup as setup_auto_import
      File "/tmp/pip-install-lxgsgu9_/pyforest/src/pyforest/__init__.py", line 2, in <module>
        from ._imports import *
      File "/tmp/pip-install-lxgsgu9_/pyforest/src/pyforest/_imports.py", line 1, in <module>
        from ._importable import LazyImport, _import_statements
      File "/tmp/pip-install-lxgsgu9_/pyforest/src/pyforest/_importable.py", line 39
        return eval(f"dir({self.__imported_name__})")
                                                   ^
    SyntaxError: invalid syntax
```

**Comment by brendalf** [comment]
Hi @ecederstrand, in the Installation step of the README says that only python 3.6 or superior.

> You need Python 3.6 or above because we love f-strings.

**Comment by ecederstrand** [comment]
Ok. I opened a new PR containing only the update to setup.cfg: https://github.com/8080labs/pyforest/pull/8

**Comment by tkrabel** [comment]
Pull request got accepted
