### ISSUE TITLE
After using pyforest the console  keep output "<IPython.core.display.Javascript object>"

### ISSUE THREAD

**Issue by OriLiMu** [8080labs/pyforest#30]
pyforest keep output <IPython.core.display.Javascript object>

* Operating System:
win 10
* Python Version: `$ python --version`
3.7.4, anaconda
* How did you install pyforest: (`pip`, `conda`, or `other (please explain)`)
pip
* Python packages: `$ pip freeze` or `$ conda list` (please include pyforest)
[packages.txt](https://github.com/8080labs/pyforest/files/4127325/test.txt)

### Description of Issue
my User import file 
```
# Add your imports here, line by line
# e.g

import datetime
from aip import AipOcr
from aip import AipSpeech
import pandas as pd
from pathlib import Path
import re
import math
import lizhelib
import wave
import struct
import pyaudio
from PIL import Image
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QEvent, Qt, pyqtSlot
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QApplication, QWidget, QHBoxLayout, QLineEdit, QLabel
from PyQt5.QtWidgets import QMainWindow, QApplication, QWidget, QPushButton, QAction, QLineEdit, QMessageBox
from colour import Color

import speech_recognition as sr
from fuzzyfinder import fuzzyfinder
from io import BytesIO
import lizhelib.win_operation
from lxml import html
from os import path
from scrapy import Selector

from scrapy.cmdline import execute
from selenium import webdriver
import PySimpleGUI as sg
import futures
import glob
import importlib
import inspect
import json
import os
import pandas as pd
import pyautogui
import random
import re
import requests
import scrapy
import shutil
import subprocess
import sys
import tempfile
import threading
import time
import win32clipboard
import wptools
import zipfile

```

Keep print IPython, 

![image](https://user-images.githubusercontent.com/11295355/73346298-93db5380-42c0-11ea-9ac4-dcfd5812c220.png)

Even I make a simple script like this still get the error. 

![image](https://user-images.githubusercontent.com/11295355/73346474-df8dfd00-42c0-11ea-8c11-3be44a86d1d0.png)

### Reproduction Steps

1. Write some simple code. 
2. Import pyforest
3. then Keep print Ipython
...

### What steps have you taken to resolve this already?

I try to delete some package in the user import file. I just leave 1 package in it which is time package

And my script is just like the code in the pic above Simple loop print, But the repeated IPython things print still happen.

How to solve it ? 

### Anything else?

...

**Comment by 8080labs** [comment]
Hi, thank you for the report and all the details. This made it easy to help you :)

Please note the following:
1. pyforest is currently only supposed to run in Jupyter Notebook/Lab. This is also the reason why you see the Display.Javascript error. This error might be suppressed via adding a flag that it is not running in Jupyter. eg via adding a new method "pyforest.deactivate_javascript()" If this method is called, a flag will be toggled that suppresses the js
2. I saw that you imported "from pyforest import *" This is the old way. In version 1.0.0 we changed this to "import pyforest"
3. Nice to see that you are using a custom imports script. Please note that you can only import one name per line. Eg "from PyQt5.QtCore import QEvent, Qt, pyqtSlot" is not supported yet. You need to write this on separate lines

**Comment by OriLiMu** [comment]
> Hi, thank you for the report and all the details. This made it easy to help you :)
> 
> Please note the following:
> 
> 1. pyforest is currently only supposed to run in Jupyter Notebook/Lab. This is also the reason why you see the Display.Javascript error. This error might be suppressed via adding a flag that it is not running in Jupyter. eg via adding a new method "pyforest.deactivate_javascript()" If this method is called, a flag will be toggled that suppresses the js
> 2. I saw that you imported "from pyforest import *" This is the old way. In version 1.0.0 we changed this to "import pyforest"
> 3. Nice to see that you are using a custom imports script. Please note that you can only import one name per line. Eg "from PyQt5.QtCore import QEvent, Qt, pyqtSlot" is not supported yet. You need to write this on separate lines

Get the error like this I git clone the repo and run setup.py still get this error. How to fix it? 

```
Traceback (most recent call last):
  File "D:/python_project/Make_Write_Easier/emoji_process/get_emoji.py", line 5, in <module>
    pyforest.deactivate_javascript()
AttributeError: module 'pyforest' has no attribute 'deactivate_javascript'
```

**Comment by 8080labs** [comment]
Yes, sorry, for the confusion. The `deactivate_javascript` function was just an idea for how we could implement this in the future. It does not exist yet. If you want this, feel free to open a pull request to add this feature :)

**Comment by 8080labs** [comment]
@woshichuanqilz are you interested in contributing a feature that suppresses the Javascript display?

**Comment by OriLiMu** [comment]
> @woshichuanqilz are you interested in contributing a feature that suppresses the Javascript display?

sorry for the delay I am very gald to help ? how should I started since I never been a contributor before what should I learn first. I use python for several years. if I can help let me know thank you for your inviting

**Comment by 8080labs** [comment]
The first step is to install pyforest locally on your computer from this repo and then have a look at the code. Once you thought through how to add the feature, you can write the new code. When you are done, you can create a pull request so that we can have a look at your code and the way that you wanted to implement this. At the beginning, this might seem a little bit intimidating but you can find a lot of good resources about the steps above on Google. I hope that helps to outline the next steps? If you have more detailed questions or are stuck somewhere, please let us know

**Comment by Amusac** [comment]
In my Jupyterlab with pyforest, output area has much blank space. this has a relation with this issue? Do you have any solution? When I uninstalled pyforest, this doesn't occur. (Sorry for my poor English.)

**Comment by Henryhaohao** [comment]
@woshichuanqilz Hello, you can comment out lines 105 to 113 in the _importable.py file, which is the "display" function in the "_update_import_cell" function definition.Then can not print <IPython.core.display.Javascript object>.

![666666](https://user-images.githubusercontent.com/36766097/110625551-88a06a00-81da-11eb-8139-6a4754b90d2f.jpg)

**Comment by hgzech** [comment]
> In my Jupyterlab with pyforest, output area has much blank space. this has a relation with this issue? Do you have any solution? When I uninstalled pyforest, this doesn't occur. (Sorry for my poor English.)

@Amusac : Yes, this seems to be related to the blank line problem.  @Henryhaohao's solution solves this problem, too.

**Comment by gamis** [comment]
This seems to fix it:
https://github.com/8080labs/pyforest/pull/49 #49

**Comment by tkrabel** [comment]
The fix has been merged
