### ISSUE TITLE
auto-completion seems not work at all when using modules imported by pyforest in pycharm

### ISSUE THREAD

**Issue by hikaruian** [8080labs/pyforest#44]
### Environment

* Operating System: win 10
* Python Version: `$ python --version` 3.7
* How did you install pyforest: (`pip`, `conda`, or `other (please explain)`)
* pip
* Python packages: `$ pip freeze` or `$ conda list` (please include pyforest)
absl-py==0.12.0
astunparse==1.6.3
backcall==0.2.0
cachetools==4.2.2
certifi==2020.12.5
chardet==4.0.0
colorama==0.4.4
decorator==5.0.7
flatbuffers==1.12
future==0.18.2
gast==0.3.3
google-auth==1.30.0
google-auth-oauthlib==0.4.4
google-pasta==0.2.0
grpcio==1.32.0
h5py==2.10.0
idna==2.10
importlib-metadata==4.0.1
ipython==7.23.1
ipython-genutils==0.2.0
jedi==0.18.0
joblib==1.0.1
Keras-Preprocessing==1.1.2
keras-tuner==1.0.2
Markdown==3.3.4
matplotlib-inline==0.1.2
numpy==1.19.5
oauthlib==3.1.0
opt-einsum==3.3.0
packaging==20.9
pandas==1.2.4
parso==0.8.2
pexpect==4.8.0
pickleshare==0.7.5
prompt-toolkit==3.0.18
protobuf==3.16.0
ptyprocess==0.7.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pyforest==1.0.3
Pygments==2.9.0
pyparsing==2.4.7
python-dateutil==2.8.1
pytz==2021.1
requests==2.25.1
requests-oauthlib==1.3.0
rsa==4.7.2
scikit-learn==0.24.2
scipy==1.6.3
six==1.15.0
tabulate==0.8.9
tensorboard==2.5.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.0
tensorflow-estimator==2.4.0
tensorflow-gpu==2.4.1
termcolor==1.1.0
terminaltables==3.1.0
threadpoolctl==2.1.0
tqdm==4.60.0
traitlets==5.0.5
typing-extensions==3.7.4.3
urllib3==1.26.4
wcwidth==0.2.5
Werkzeug==1.0.1
wrapt==1.12.1
zipp==3.4.1

### Description of Issue
when coding in pycharm, i use pyforest to import all libs like pandas,numpy etc.But auto-completion seems not work at all in pycharm. Somebody knows why and how to do?

**Comment by tkrabel** [comment]
Hi @hikaruian,

I checked auto-completion at least for Jupyter Notebook (just to have a benchmark) and there it worked.
Not sure why pycharm auto-completion doesn't work, but likely it's not simply using IPython to inspect modules.
