### ISSUE TITLE
Running Pyforest on Anaconda3 Jupyter

### ISSUE THREAD

**Issue by cyrus-muriithi** [8080labs/pyforest#5]
I am running Python 3.7.4, and Anaconda3.
I have installed pyforest using pip install pyforest

when i run from pyforest import * in my jupyter, i get this error:

ModuleNotFoundError Traceback (most recent call last)
in
----> 1 from pyforest import *

ModuleNotFoundError: No module named 'pyforest'

Also when i run pip freeze i also get this warning
~(master*) » pip3.7 freeze cyrusmuriithi@Cyruss-MacBook-Pro
WARNING: Could not generate requirement for distribution -forest 0.1.1 (/usr/local/lib/python3.7/site-packages): Parse error at "'-forest='": Expected W:(abcd...)
WARNING: Could not generate requirement for distribution -yforest 0.1.1 (/usr/local/lib/python3.7/site-packages): Parse error at "'-yforest'": Expected W:(abcd...)
WARNING: Could not generate requirement for distribution -.forest 0.1.1 (/usr/local/lib/python3.7/site-packages): Parse error at "'-.forest'": Expected W:(abcd...)
WARNING: Could not generate requirement for distribution - forest (/usr/local/lib/python3.7/site-packages): Parse error at "'-===fore'": Expected W:(abcd...)
pyforest==0.1.1

What could be the issue that i cannot run pyforest

**Comment by guido611** [comment]
Hi @cyrus-muriithi, 
please check your `/usr/local/lib/python3.7/site-packages` folder and remove the corrupt distributions (`-forest 0.1.1` etc.).
Then validate that `pip freeze` is working again.
Maybe you need to re-install pyforest as well. Make sure you're using `pip3` for the installation.

**Comment by cyrus-muriithi** [comment]
I have done exactly that, but when  i run my code (`from pyforest import *`) in my jupyter,
 i still get the error  `ModuleNotFoundError: No module named 'pyforest`
