### ISSUE TITLE
How can I use it in .py file?

### ISSUE THREAD

**Issue by gorodion** [8080labs/pyforest#54]
Should I just put `import pyforest` in a .py file to make it work? In this case nothing is happening

**Comment by 8080labs** [comment]
Pyforest does only work in Jupyter notebooks so far.

I never thought about having it in .py files as well but it totally makes sense.

However, this requires a different implementation. Which code editor do you use?

Are you interested and/or available for working on this yourself?

**Comment by tkrabel** [comment]
closed due to inactivity
