### ISSUE TITLE
adding mailbox package 

### ISSUE THREAD

**Issue by ghost** [8080labs/pyforest#55]
### Environment

* Operating System:
* Python Version: `$ python --version`
* How did you install pyforest: pi[ (`pip`, `conda`, or `other (please explain)`)
* Python packages: `$ pip freeze` or `$ conda list` (please include pyforest)

### Description of Issue

I guess the mailbox library is not imported in pyforest. So, I have raised an issue to add this package. 
"import mailbox"

**Comment by tkrabel** [comment]
Pls note in the README that you can add lazy imports yourself easily. We only want to add very common packages to the lazy import list in the package. The rest can be added yourself.
