### ISSUE TITLE
It missed a commonly-used package "random"

### ISSUE THREAD

**Issue by PKUfudawei** [8080labs/pyforest#57]
I made a pull request from my repository, please check if it meets your standard. See this [pull request](https://github.com/8080labs/pyforest/pull/56)

**Comment by PKUfudawei** [comment]
Hi @8080labs , I'm looking forward to hearing your opinion about whether to add this package in pyforest, thanks a lot!

**Comment by tkrabel** [comment]
@PKUfudawei thanks for the PR and sorry for the late reply. I merged it!
